.\" Manpage for tldr.
.\" Contact ag@arvid.io to correct errors or typos.
.TH TLDR 1
.SH NAME
tldr \- A collection of simplified and community-driven man pages.
.SH SYNOPSIS
.B tldr
[\fB\-C\fR] [\fB\-v\fR] [\fB\-c\fR] [\fB\-u\fR] [\fB\-l\fR] [\fB\-p\fR \fIPLATFORM\fR]... [\fB\-r\fR \fIPATH\fR] \fIPAGE\fR
.SH DESCRIPTION
tldr is a collection of simplified and community-driven man pages for commonly used command-line tools.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print help to standard output and exit.
.TP
.BR \-C ", " \-\-color
Force color display.
.TP
.BR \-v ", " \-\-version
Output version information and exit.
.TP
.BR \-u ", " \-\-update
Update the local database and exit.
.TP
.BR \-p ", " \-\-platform=\fIPLATFORM\fR
Select platform, supported platforms are \fIlinux\fR / \fIosx\fR / \fIsunos\fR / \fIwindows\fR / \fIcommon\fR.
.TP
.BR \-r ", " \-\-render=\fIPATH\fR
Render a local page for testing purposes.
.TP
.BR \-c ", " \-\-clear-cache
Remove the local database and exit.
.TP
.BR \-l ", " \-\-list
List all entries in the local database.
.TP
.BR \-V ", " \-\-verbose
Print verbose output (when used with \fB\-c\fR or \fB\-u\fR).
.SH EXIT STATUS
0 on success, any other positive value otherwise.
.SH SEE ALSO
The source is available at:
<https://github.com/tldr-pages/tldr-c-client>.
.SH REPORTING BUGS
Report bugs through the GitHub repository:
<https://github.com/tldr-pages/tldr-c-client>.
.SH COPYRIGHT
The MIT License (MIT)

Copyright (c) 2016 Arvid Gerstmann.
