.\" Manpage for tldr.
.\" Contact ag@arvid.io to correct errors or typos.
.TH TLDR 1
.SH NAME
tldr \- A collection of simplified and community-driven man pages.
.SH SYNOPSIS
.B tldr
[\fB\-v\fR] [\fB\-u\fR] [\fB\-c\fR] [\fIOPTION\fR]... [\fIPAGE\fR]
.SH DESCRIPTION
tldr is a collection of simplified and community-driven man pages, for commonly
used commandline tools.
.SH OPTIONS
.TP
.BR \-v
verbose output (when used with \fB\-u\fR or \fB\-c\fR)
.TP
.BR \-v ", " \-\-version
output version information and exit
.TP
.BR \-h ", " \-\-help
display help and exit
.TP
.BR \-u ", " \-\-update
update local database and exit
.TP
.BR \-c ", " \-\-clear-cache
remove local database and exit
.TP
\fB\-p\fR, \fB\-\-platform\fR=\fIPLATFORM\fR
select platform, supported are \fIlinux\fR / \fIosx\fR / \fIsunos\fR / \fIwindows\fR / \fIcommon\fR
.TP
.BR \-\-linux
show command page for Linux
.TP
.BR \-\-osx
show command page for OSX
.TP
.BR \-\-sunos
show command page for SunOS
.TP
\fB\-r\fR, \fB\-\-render\fR=\fIPATH\fR
render a local page for testing purposes
.SH EXIT STATUS
0 on success, any other positive value otherwise
.SH SEE ALSO
The source is available at:
.UR "https://github.com/tldr-pages/tldr-cpp-client"
.UE .
.SH REPORTING BUGS
Report bugs through the Github repository:
.UR "https://github.com/tldr-pages/tldr-cpp-client"
.UE .
.SH COPYRIGHT
The MIT License (MIT)

Copyright (c) 2016 Arvid Gerstmann.

