language: c
sudo: required

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libzip-dev
            - pkg-config

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          sudo apt-get update -qq;
          sudo apt-get install -qq libcurl4-openssl-dev libzip-dev pkg-config;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew update;
          brew install curl libzip;
      fi

script:
    - make V=1 DEBUG=

